version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web-app"
    schedule:
      interval: "daily"
    groups:
      non-major:
        update-types: ["patch", "minor"]
        patterns: ["*"]
